services:
  - type: worker
    name: garajhub-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        value: "@GarajHub_uz"
      - key: ADMIN_ID
        value: "7903688837"